version: '3'

services:

  www:
    image: nginx:1.13-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/conf.d:/etc/nginx/conf.d:ro
      - ./conf/ssl:/etc/ssl:ro
      - ./logs:/var/log/nginx:rw
      - ./www:/usr/share/nginx/html:ro
    depends_on:
      - php
      - db
    restart: unless-stopped

  php:
    image: zierf/php:7-fpm-alpine
    #ports:
    #  - '9004:9004'
    volumes:
      - ./www:/usr/share/nginx/html:rw
    restart: unless-stopped

  db:
    image: mariadb:10.3
    #ports:
    #  - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./conf/initdb.d:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    env_file: .env

volumes:
  db:
